# -*- coding: utf-8 -*-
"""2_Data_wrangling_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eC6JYqds7mMcCd3Z8xsSqyNSM8Q6tNsN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/academic_performance (2).csv")

df.head()

# Missing values check
print("\nMissing values:")
df.isnull().sum()

#Handle Missing Values
df['Maths'] = df['Maths'].fillna(df['Maths'].mean())
df['Science'] = df['Science'].fillna(df['Science'].mean())
df['English'] = df['English'].fillna(df['English'].mean())
df['Attendance()'] = df['Attendance'].fillna(df['Attendance'].mean())

df.isnull().sum()

df

#Detect & Handle Outliers- IQR
def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    data[column] = np.where(data[column] < lower, lower, data[column])
    data[column] = np.where(data[column] > upper, upper, data[column])

# Apply to numeric columns
for col in ['Maths', 'Science', 'English', 'Attendance']:
    remove_outliers_iqr(df, col)
df[['Maths', 'Science', 'English', 'Attendance']].describe()

df.boxplot(column=['Maths', 'Science', 'English', 'Attendance'])
plt.show()

#Data Transformation-Log Transformation (for normalization)
df['Maths_log'] = np.log1p(df['Maths'])
df[['Maths', 'Maths_log']].head()

#Optional - Min-Max Scaling (better for comparison)
df['Maths_scaled'] = (df['Maths'] - df['Maths'].min()) / (df['Maths'].max() - df['Maths'].min())
df[['Maths', 'Maths_log']].describe()

df.head()

#Before vs After comparison
print("Before transformation:")
print(df['Maths'].head())

print("After transformation:")
print(df['Maths_log'].head())