# -*- coding: utf-8 -*-
"""Descriptive_Statistics-Measures_Central Tendency_variability .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txFKrxNQjceGf6IYGR5tYYQ3lDuXPd1v
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Iris.csv")
df.head()

"""**Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and quantitative variable is income, then provide summary statistics of income grouped by the age groups.**
"""

#Mean Grouped by Species
df.groupby('Species').mean()

#Median Grouped by Species
df.groupby('Species').median()

#Minimum Values Grouped by Species
df.groupby('Species').min()

#Maximum Values Grouped by Species
df.groupby('Species').max()

#Standard Deviation Grouped by Species
df.groupby('Species').std()

"""**Create a list that contains a numeric value for each response to the categorical variable.**"""

#Sepal Length values for each species
setosa = df[df['Species'] == 'Iris-setosa']['SepalLengthCm'].tolist()
versicolor = df[df['Species'] == 'Iris-versicolor']['SepalLengthCm'].tolist()
virginica = df[df['Species'] == 'Iris-virginica']['SepalLengthCm'].tolist()
print("Setosa:", setosa)
print("Versicolor:", versicolor)
print("Virginica:", virginica)

"""**Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ of
iris.csv dataset.**
"""

#Filter Species Data
setosa = df[df['Species'] == 'Iris-setosa']
versicolor = df[df['Species'] == 'Iris-versicolor']
virginica = df[df['Species'] == 'Iris-virginica']

#Statistical Details of Iris-setosa
print("Iris-setosa Statistics")
setosa.describe()

#Statistical Details of Iris-versicolor
print("Iris-versicolor Statistics")
versicolor.describe()

#Statistical Details of Iris-virginica
print("Iris-virginica Statistics")
virginica.describe()

"""**Percentile Calculation**"""

print("Setosa Percentiles")
print(np.percentile(
    setosa['SepalLengthCm'],
    [25, 50, 75]
))

print("Versicolor Percentiles")
print(np.percentile(
    versicolor['SepalLengthCm'],
    [25, 50, 75]
))

print("Virginica Percentiles")
print(np.percentile(
    virginica['SepalLengthCm'],
    [25, 50, 75]
))

#Complete Statistical Summary
df.groupby('Species').describe()