# -*- coding: utf-8 -*-
"""6_Data_analytics_III.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4Yi1fi6W1YinfN-MWTtsN_tVowUE_oZ

https://www.kaggle.com/datasets/uciml/iris?utm_source
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

df = pd.read_csv("/content/Iris.csv")
df.head()

df.info()

#Define Features and Target
# Features

X = df.iloc[:, 1:5]

# Target

y = df.iloc[:, 5]

#Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
#Train Naïve Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Predict Test Data
y_pred = model.predict(X_test)
print(y_pred)

#Create Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

#Calculate TP, FP, TN, FN
TP = cm[0][0]
FP = cm[:,0].sum() - TP
FN = cm[0,:].sum() - TP
TN = cm.sum() - (TP + FP + FN)
print("TP =", TP)
print("FP =", FP)
print("TN =", TN)
print("FN =", FN)

#Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
print("Accuracy =", accuracy)

#Error Rate
error_rate = (FP + FN) / (TP + TN + FP + FN)
print("Error Rate =", error_rate)

#Precision
precision = TP / (TP + FP)
print("Precision =", precision)

#Recall
recall = TP / (TP + FN)
print("Recall =", recall)