# -*- coding: utf-8 -*-
"""7_Text_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbNChukdi8iiD8_X6GrZZEEsFSiHC_D6
"""

pip install nltk scikit-learn

import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

#Sample Document
text = """
Data Science is an interdisciplinary field.
It uses scientific methods, algorithms and systems.
Machine learning is an important part of Data Science.
"""
print("Original Text:")
print(text)

#Tokenization
tokens = word_tokenize(text)
print("\nTokens:")
print(tokens)

#POS Tagging
pos_tags = pos_tag(tokens)
print(pos_tags)

# Stopword Removal
stop_words = set(stopwords.words('english'))
filtered_words = [
    word for word in tokens
    if word.lower() not in stop_words
]
print("Filtered Words:", filtered_words)

# Stemming
stemmer = PorterStemmer()
stemmed_words = [
    stemmer.stem(word)
    for word in filtered_words
]
print("Stemmed Words:", stemmed_words)

# Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_words = [
    lemmatizer.lemmatize(word)
    for word in filtered_words
]
print("Lemmatized Words:", lemmatized_words)

# TF-IDF
documents = [
    "Data Science uses machine learning",
    "Machine learning uses algorithms",
    "Data Science uses data analysis"
]

#Calculate TF-IDF
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

#Display Feature Names
print("Feature Names:")
print(vectorizer.get_feature_names_out())

#Display TF-IDF Matrix
print("TF-IDF Matrix:")
print(tfidf_matrix.toarray())
