# -*- coding: utf-8 -*-
"""8_Data_Visualization_I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqWw0KTjTDOsrfwC2zBEga4WX_QzKCV0?usp=sharing
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = sns.load_dataset('titanic')
df.head()

df.info()

#Check Missing Values
df.isnull().sum()

"""**Find Patterns in Data**"""

#Survival Count
sns.countplot(x='survived', data=df)
plt.title("Survival Count")
plt.show()

#Survival by Gender
sns.countplot(x='survived', hue='sex', data=df)
plt.title("Survival by Gender")
plt.show()

#Survival by Passenger Class
sns.countplot(x='survived', hue='class', data=df)
plt.title("Survival by Passenger Class")
plt.show()

#Age Distribution
sns.histplot(df['age'], bins=30)
plt.title("Age Distribution")
plt.show()

"""**Write a code to check how the price of the ticket (column name: 'fare') for each passenger
is distributed by plotting a histogram.**
"""

sns.histplot(df['fare'], bins=30, kde=True)
plt.title("Fare Distribution")
plt.show()
