# -*- coding: utf-8 -*-
"""8_Data_Visualization_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKNWLV_fd30hg_Y5PIqhzXkPjzNcmO6s
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = sns.load_dataset('titanic')
df.head()

df.info()

#Plot Box Plot
plt.figure(figsize=(8,6))
sns.boxplot(
    x='sex',
    y='age',
    hue='survived',
    data=df
)
plt.title("Age Distribution by Gender and Survival")
plt.xlabel("Gender")
plt.ylabel("Age")
plt.show()
