# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zi9vMHZa4dgTHV2dRRarVAWInTq5gNNn
"""

# Importing required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading dataset

df = pd.read_csv("/content/Titanic-Dataset.csv")

# Display first 5 rows

df.head()

# display last 5 rows
df.tail()

# Checking missing values
df.isnull()

# sum of missing values
df.isnull().sum()

# no null, value exists
df.notnull()

df.notnull().sum()

# Statistical summary

df.describe()

# Dimensions of dataset

df.shape

# Checking data types

df.dtypes

# Convert Survived column into category

df['Survived'] = df['Survived'].astype('category')

# Convert Sex column into category

df['Sex'] = df['Sex'].astype('category')

# Checking updated data types

df.dtypes

# Normalizing Fare column

df['Fare_Normalized'] = (
    (df['Fare'] - df['Fare'].min()) /
    (df['Fare'].max() - df['Fare'].min())
)

df[['Fare', 'Fare_Normalized']].head()

# Convert Sex column into numeric values

df['Sex'] = df['Sex'].map({
    'male': 0,
    'female': 1
})

df[['Sex']].head()

# One-hot encoding

df = pd.get_dummies(df, columns=['Embarked'])
df.head()

df.info()

display(df.dtypes.to_frame(name='Data Type'))
display(df.isnull().sum().to_frame(name='Missing Values'))