# -*- coding: utf-8 -*-
"""data_wrangling_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zi9vMHZa4dgTHV2dRRarVAWInTq5gNNn
"""

# Importing required libraries
import pandas as pd
import numpy as np

# Loading dataset
df = pd.read_csv("/content/Titanic-Dataset.csv")

# Display first 5 rows
df.head()

# display last 5 rows
df.tail()

"""**Data Preprocessing: check for missing values in the data using pandas isnull(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables etc.
Check the dimensions of the data frame.**
"""

# Checking missing values
df.isnull()

# sum of missing values
df.isnull().sum()

# no null, value exists
df.notnull()

#no null, value exists sum
df.notnull().sum()

# Statistical summary
df.describe()

# Dimensions of dataset
df.shape

"""**Data Formatting and Data Normalization: Summarize the types of variables by checking the
data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set.
If variables are not in the correct data type, apply proper type conversions.**
"""

# Checking data types
df.dtypes

# Convert Survived column into category
df['Survived'] = df['Survived'].astype('category')

# Convert Sex column into category
df['Sex'] = df['Sex'].astype('category')

# Checking updated data types
df.dtypes

# Normalizing Fare column
df['Fare_Normalized'] = (
    (df['Fare'] - df['Fare'].min()) /
    (df['Fare'].max() - df['Fare'].min()))
df[['Fare', 'Fare_Normalized']].head()

"""**Turn categorical variables into quantitative variables in Python.**"""

# Convert Sex column into numeric values
df['Sex'] = df['Sex'].map({
    'male': 0,
    'female': 1
})
df[['Sex']].head()

# One-hot encoding
df = pd.get_dummies(df, columns=['Embarked'])
df.head()

df.info()