# -*- coding: utf-8 -*-
"""Data Analytics I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKx11fGQ3Htuiz4yvTsQidjQy2fmtXSb

https://www.kaggle.com/datasets/vikrishnan/boston-house-prices
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("/content/HousingData.csv")
df.head()

#Check shape
df.shape

#Check columns
df.columns

#Check missing values
df.isnull().sum()

#Handle Missing Values
df = df.fillna(df.mean())
df.isnull().sum()

#Define Features and Target
X = df.drop('MEDV', axis=1)
y = df['MEDV']

#Split Dataset into Training and Testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)

#Create Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

#Predict House Prices
y_pred = model.predict(X_test)
print(y_pred[:10])

#Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

#Check Accuracy (R² Score)
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

#Compare Actual vs Predicted Values
result = pd.DataFrame({
    'Actual Price': y_test,
    'Predicted Price': y_pred
})

result.head(10)

#Plot Actual vs Predicted
plt.scatter(y_test, y_pred)

plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted House Prices")

plt.show()